[package]
name = "allele"
description = "A modular framework for implementing and running genetic algorithm simulations"
repository = "https://github.com/regexident/allele"
keywords = ["genetic", "evolutionary", "algorithm"]
license = "MIT/Apache-2.0"
edition = "2024"
rust-version = "1.85.1"
version = "0.8.0"

[package.metadata.docs.rs]
all-features = true

[dependencies]
humantime = "2"
rand = { version = "0.10", default-features = false, features = ["getrandom"] }
rand_xoshiro = "0.8"
fixedbitset = { version = "0.5", optional = true }
smallvec = { version = "1", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = { version = "1", optional = true }

[target.'cfg(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi"))))'.dependencies]
wasm-bindgen_ = { version = "0.2", package = "wasm-bindgen", optional = true }
getrandom = { version = "0.4", features = ["js", "wasm-bindgen"] }

[dev-dependencies]
criterion = "=0.3.6"
proptest = "=1.11.0"
test-strategy = "=0.4.5"
version-sync = "=0.9.5"

[features]
wasm-bindgen = ["wasm-bindgen_"]
parallel = ["rayon"]

[lib]
bench = false

[[bench]]
name = "index_of_value_in_vector"
harness = false

[[bench]]
name = "genome_builder"
harness = false

[[bench]]
name = "population_builder"
harness = false

[[example]]
name = "knapsack"
path = "examples/knapsack/main.rs"
required-features = [ "smallvec" ]

[[example]]
name = "monkeys"
path = "examples/monkeys/main.rs"

[[example]]
name = "queens"
path = "examples/queens/main.rs"
